# Generated by Django 4.2 on 2024-12-17 23:47

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology')], max_length=100, verbose_name='Program of Study')),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('transferee', 'Transferee')], max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('soc_fee', models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date_enrolled', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CS Student',
                'verbose_name_plural': 'CS Students',
                'db_table': 'app_cs_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppCsStudentsSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
                ('sub6', models.CharField(max_length=100)),
                ('sub7', models.CharField(max_length=100)),
                ('sub8', models.CharField(max_length=100)),
                ('sub9', models.CharField(max_length=100)),
                ('encoder', models.CharField(max_length=100)),
                ('total_units', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'app_cs_students_sub',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppItStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology')], max_length=100, verbose_name='Program of Study')),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('transferee', 'Transferee')], max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=2)),
                ('section', models.CharField(max_length=50)),
                ('soc_fee', models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid')], max_length=50)),
                ('date_enrolled', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IT Student',
                'verbose_name_plural': 'IT Students',
                'db_table': 'app_it_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppItStudentsSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
                ('sub6', models.CharField(max_length=100)),
                ('sub7', models.CharField(max_length=100)),
                ('sub8', models.CharField(max_length=100)),
                ('sub9', models.CharField(max_length=100)),
                ('encoder', models.CharField(max_length=100)),
                ('total_units', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'app_it_students_sub',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=100)),
                ('lab_units', models.IntegerField()),
                ('lec_units', models.IntegerField()),
                ('year_level', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('cs', models.CharField(max_length=50)),
                ('it', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_sub',
                'managed': True,
            },
        ),
    ]
