# Generated by Django 5.1.3 on 2024-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('course', models.TextField()),
                ('year_level', models.IntegerField()),
                ('status', models.TextField()),
                ('enrollment_status', models.TextField()),
            ],
            options={
                'db_table': 'cs_students',
                'managed': False,
            },
        ),
    ]
