# Generated by Django 5.1.3 on 2024-11-26 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology')], max_length=100, verbose_name='Program of Study')),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], max_length=2)),
                ('section', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(blank=True, help_text='Optional CS specialization', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'CS Student',
                'verbose_name_plural': 'CS Students',
                'db_table': 'app_cs_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppItStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology')], max_length=100, verbose_name='Program of Study')),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], max_length=2)),
                ('section', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.CharField(blank=True, help_text='Optional IT track', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IT Student',
                'verbose_name_plural': 'IT Students',
                'db_table': 'app_it_students',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CsStudents',
        ),
    ]
