# Generated by Django 5.1.3 on 2024-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appcsstudents_appitstudents_delete_csstudents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcsstudents',
            options={'managed': True, 'verbose_name': 'CS Student', 'verbose_name_plural': 'CS Students'},
        ),
        migrations.AlterModelOptions(
            name='appitstudents',
            options={'managed': True, 'verbose_name': 'IT Student', 'verbose_name_plural': 'IT Students'},
        ),
    ]
